### ISSUE TITLE
Unhandled error starting denero's server

### ISSUE THREAD

**Issue by ryanlovett** [data-8/jupyterhub-deploy#18]
John reported this just before lab. This is where I attempted to launch his container as admin:
```
[I 2016-02-10 19:10:08.425 JupyterHub swarmspawner:36] num_node_info: [['node1', '10.0.0.4:2376'], ['node2', '10.0.0.8:2376'], ['node3', '10.0.0.9:2376'], ['node4', '10.0.0.10:2376'], ['node5', '10.0.0.11:2376'], ['node6', '10.0.0.12:2376'], ['node7', '10.0.0.13:2376'], ['node8', '10.0.0.14:2376'], ['node9', '10.0.0.16:2376'], ['node10', '10.0.0.23:2376'], ['node11', '10.0.0.17:2376'], ['node12', '10.0.0.18:2376'], ['node13', '10.0.0.19:2376'], ['node14', '10.0.0.20:2376'], ['node15', '10.0.0.21:2376'], ['node16', '10.0.0.22:2376'], ['node17', '10.0.0.15:2376'], ['node18', '10.0.0.24:2376'], ['node19', '10.0.0.25:2376'], ['node21', '10.0.0.27:2376'], ['node22', '10.0.0.28:2376'], ['node23', '10.0.0.29:2376'], ['node24', '10.0.0.30:2376'], ['node25', '10.0.0.31:2376'], ['node26', '10.0.0.32:2376'], ['node27', '10.0.0.33:2376'], ['node28', '10.0.0.34:2376'], ['node29', '10.0.0.35:2376'], ['node30', '10.0.0.36:2376'], ['node31', '10.0.0.37:2376'], ['node32', '10.0.0.38:2376'], ['node33', '10.0.0.41:2376'], ['node34', '10.0.0.42:2376'], ['node35', '10.0.0.43:2376']]
[I 2016-02-10 19:10:08.428 JupyterHub swarmspawner:56] starting container: image:None
[I 2016-02-10 19:10:08.432 JupyterHub dockerspawner:276] Container 'jupyter-denero' is gone
[I 2016-02-10 19:10:09.146 JupyterHub dockerspawner:328] Created container 'jupyter-denero' (id: ccfb3dc) from image systemuser
[I 2016-02-10 19:10:09.147 JupyterHub dockerspawner:338] Starting container 'jupyter-denero' (id: ccfb3dc)
[E 2016-02-10 19:10:11.947 JupyterHub user:192] Unhandled error starting denero's server: 'node35'
[I 2016-02-10 19:10:12.280 JupyterHub dockerspawner:362] Stopping container jupyter-denero (id: ccfb3dc)
[I 2016-02-10 19:10:14.043 JupyterHub dockerspawner:368] Removing container jupyter-denero (id: ccfb3dc)
[E 2016-02-10 19:10:16.078 JupyterHub web:1524] Uncaught exception POST /hub/api/users/denero/server (128.32.135.205)
    HTTPServerRequest(protocol='http', host='data8.berkeley.edu', method='POST', uri='/hub/api/users/denero/server', version='HTTP/1.1', remote_ip='128.32.135.205', headers={'X-Forwarded-Port': '80', 'Host': 'data8.berkeley.edu', 'Content-Type': 'application/json', 'X-Requested-With': 'XMLHttpRequest', 'X-Forwarded-For': '128.32.135.205,10.0.0.5', 'Accept': '*/*', 'X-Nginx-Proxy': 'true', 'Cookie': 'jupyter-hub-token="<snip>"; ss_cid=<snip>; __utma=41573937.488200877.1417645850.1436921113.1450401192.4; __utmz=41573937.1436921113.3.1.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); WFC_INSTANCE=<snip>; WFC_ANALYTICS=<snip>; WFC_USER=<snip>; deeplocation=SC2_DEEP_UC; _ga=GA1.2.488200877.1417645850', 'X-Real-Ip': '128.32.135.205', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'close', 'Referer': 'https://data8.berkeley.edu/hub/admin?sort=running&order=desc&', 'Accept-Language': 'en-US,en;q=0.8', 'Origin': 'https://data8.berkeley.edu', 'Content-Length': '0', 'Dnt': '1', 'X-Forwarded-Proto': 'http', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36'})
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/tornado/web.py", line 1445, in _execute
        result = yield result
      File "/opt/conda/lib/python3.5/types.py", line 179, in throw
        return self.__wrapped.throw(tp, *rest)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/apihandlers/users.py", line 170, in post
        yield self.spawn_single_user(user, options=options)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 296, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 202, in spawn
        raise e
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 183, in spawn
        yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/srv/oauthenticator/swarmspawner.py", line 63, in start
        self.user.server.ip = self.node_info[name]
    KeyError: 'node35'
E 2016-02-10 19:10:16.105 JupyterHub log:99] {
      "X-Forwarded-Port": "80",
      "Host": "data8.berkeley.edu",
      "Content-Type": "application/json",
      "X-Requested-With": "XMLHttpRequest",
      "X-Forwarded-For": "128.32.135.205,10.0.0.5",
      "Accept": "*/*",
      "X-Nginx-Proxy": "true",
      "Cookie": "jupyter-hub-token=\"2|1:0|10:1454378753|17:jupyter-hub-token|<snip>"; ss_cid=<snip>; __utma=41573937.488200877.1417645850.1436921113.1450401192.4; __utmz=41573937.1436921113.3.1.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); WFC_INSTANCE=<snip>; WFC_ANALYTICS=<snip>; WFC_USER=<snip>; deeplocation=SC2_DEEP_UC; _ga=GA1.2.488200877.1417645850",
      "X-Real-Ip": "128.32.135.205",
      "Accept-Encoding": "gzip, deflate",
      "Connection": "close",
      "Referer": "https://data8.berkeley.edu/hub/admin?sort=running&order=desc&",
      "Accept-Language": "en-US,en;q=0.8",
      "Origin": "https://data8.berkeley.edu",
      "Content-Length": "0",
      "Dnt": "1",
      "X-Forwarded-Proto": "http",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36"
    }
[E 2016-02-10 19:10:16.106 JupyterHub log:100] 500 POST /hub/api/users/denero/server (rylo@128.32.135.205) 7931.65ms
```

**Comment by ryanlovett** [comment]
It can't find node35 in the swarm spawner even though moments earlier it was available.

This feels like an atomicity issue.

**Comment by ryanlovett** [comment]
Closing due to JupyterHub 0.5.0 upgrade.
