### ISSUE TITLE
docker daemons hang on nodes

### ISSUE THREAD

**Issue by ryanlovett** [data-8/jupyterhub-deploy#19]
On node35, "docker ps" hangs. This interferes with the hubs ability to communicate with its running containers. Restarting docker doesn't fix it.

```
root@node35:~# start docker
docker start/running, process 15485
root@node35:~# tail /var/log/upstart/docker.log
INFO[58874] GET /v1.19/images/json?filters=%7B%22dangling%22%3A%5B%22true%22%5D%7D
INFO[59056] GET /containers/da8fc50b3f8dd61126cf2f8d82d0747a6f69bfc6b0a53fd3ac784e7bbc84cc71/json
INFO[59185] GET /v1.19/containers/json
INFO[59201] Processing signal 'terminated'
INFO[59211] Container ff0ef0a06d192f85aaa369c440df7af3dd92c58cb6c73bd305ee7522d9c5c9a4 failed to exit within 10 seconds of SIGTERM - using the force
ERRO[59216] Force shutdown daemon
WARN[0000] Running modprobe bridge nf_nat failed with message: , error: exit status 1
INFO[0000] Loading containers: start.
..............INFO[0000] Listening for HTTP on tcp (0.0.0.0:2376)
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
root@node35:~# docker ps
^Croot@node35:~# stop docker
docker stop/waiting
root@node35:~# ps aux | grep docker
root     15520  0.0  0.0   4336  1456 ?        D    18:20   0:00 auplink /var/lib/docker/aufs/mnt/ff0ef0a06d192f85aaa369c440df7af3dd92c58cb6c73bd305ee7522d9c5c9a4 flush
root     15541  0.0  0.0  10468  2192 pts/3    S+   18:22   0:00 grep --color=auto docker
```

**Comment by jandersonlee** [comment]
What about restarting node35?

Jeff

**Comment by ryanlovett** [comment]
Doing so. 'reboot' does nothing so I have to reboot from the azure console. node30 is also hanging at the moment.

I had to reboot node35 yesterday. I think I'll destroy the two hangers and restart the swarm without them in the pool

**Comment by ryanlovett** [comment]
This happened for node33 today. When it came up, docker was responsive but the swarm indicated
"Engine no longer exists" for the node. I had to restart swarm to get it to show no error.

After the swarm began to assign containers to it however, user's jobs were not actually being started correctly. See log entry below. I've removed node33 from the swarm.

```
[E 2016-02-16 02:13:16.633 JupyterHub gen:871] Exception in Future <tornado.concurrent.Future object at 0x7f2df01cc940> after timeout
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 867, in error_callback
        future.result()
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 202, in spawn
        raise e
      File "/opt/conda/lib/python3.5/site-packages/jupyterhub/user.py", line 183, in spawn
        yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/srv/oauthenticator/swarmspawner.py", line 63, in start
        self.user.server.ip = self.node_info[name]
    KeyError: 'node33'
```

**Comment by ryanlovett** [comment]
A process is currently hanging on node4. Rather than rebooting the node or trying to restart docker to clean out the corresponding container, I renamed the container, `docker rename jupyter-jinlee8502 jupyter-BAD-jinlee8502`. The container ID is still being tracked by swarm however.

**Comment by ryanlovett** [comment]
I'm pulling node4 out of swarm until its existing servers finish and the node can be rebooted.
