### ISSUE TITLE
Hub will fail to start when a single node malfunctions

### ISSUE THREAD

**Issue by ryanlovett** [data-8/jupyterhub-deploy#8]
I came across this tonight. I've temporarily disabled node12 as a workaround.

```[E 2016-01-27 07:45:05.386 JupyterHub app:1113]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/app.py", line 1110, in launch_instance_async
        yield self.initialize(argv)
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/app.py", line 930, in initialize
        yield self.init_spawners()
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/app.py", line 729, in init_spawners
        status = yield spawner.poll()
      File "/usr/local/lib/python3.4/dist-packages/dockerspawner/dockerspawner.py", line 245, in poll
        container = yield self.get_container()
      File "/usr/local/lib/python3.4/dist-packages/dockerspawner/dockerspawner.py", line 271, in get_container
        'inspect_container', self.container_name
      File "/usr/lib/python3.4/concurrent/futures/_base.py", line 395, in result
        return self.__get_result()
      File "/usr/lib/python3.4/concurrent/futures/_base.py", line 354, in __get_result
        raise self._exception
      File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/usr/local/lib/python3.4/dist-packages/dockerspawner/dockerspawner.py", line 233, in _docker
        return m(*args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/docker/utils/decorators.py", line 20, in wrapped
        return f(self, resource_id, *args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/docker/client.py", line 510, in inspect_container
        True)
      File "/usr/local/lib/python3.4/dist-packages/docker/clientbase.py", line 108, in _result
        self._raise_for_status(response)
      File "/usr/local/lib/python3.4/dist-packages/docker/clientbase.py", line 104, in _raise_for_status
        raise errors.APIError(e, response, explanation=explanation)
    docker.errors.APIError: 500 Server Error: Internal Server Error ("b'Container jupyter-melodyhhuang running on unhealthy node node12'")
```

**Comment by ryanlovett** [comment]
Hit by this again with node34.
